### ISSUE TITLE
Logging in controllers

### ISSUE THREAD

**Issue by jorbor** [alvaromongon/InventorySystem#6]
All of the methods in ItemsController use a catch-all log exception. Is there a better way to do this?

**Comment by alvaromongon** [comment]
It is actually better to create an attribute to handle exceptions in the controllers, returning a HttpResponseException. We actually do like that. But in this case because I had to build just three controllers I didn't think about but. In any case, since I was supposed to be writing production quality code. It should be there.

**Comment by jorbor** [comment]
Can you elaborate? What would you name this attribute? What classes or methods would you place it on? What would return HttpResponseException?

**Comment by alvaromongon** [comment]
I have created a pull request with some changes. trying to address the problems found: [https://github.com/alvaromongon/InventorySystem/pull/9]
