### ISSUE TITLE
HandlersManager

### ISSUE THREAD

**Issue by jorbor** [alvaromongon/InventorySystem#8]
Why did you decide to put exception handling within handlers and not handle within HandlersManager? Do you think it's ok to rely on BaseHandler handling exceptions?

**Comment by alvaromongon** [comment]
The idea is to handle the exception and log it in the handle inside the loop, because I do not want to block the rest of the posts.

If the error is affecting the whole DoWork method, I handle it, log the appropriate exception and throw it up in case the BaseHandler has something to do about it. But since I do not have a handler of the base handler, I should not throw the exception up to the BaseHandler or otherwise the keep running loop will finished. 

Good catch!
